### ISSUE TITLE
DAISIE_MW_ML not functioning in develop branch

### ISSUE THREAD

**Issue by Neves-P** [rsetienne/DAISIE#109]
The example at:

https://github.com/rsetienne/DAISIE/blob/dd54db21a841a182fa6b44796fe20ea22916781a/R/DAISIE_MW_ML.R#L335-L358

runs fine when called from the `master` branch, but returns 
```
You are optimizing lambda_c0 mu_0 x gamma_0 alpha lambda_a0 beta d0 
You are fixing y K_0 z 
Calculating the likelihood for the initial parameters. 
The loglikelihood for the initial parameter values is -Inf 
The initial parameter values have a likelihood that is equal to 0 or below machine precision. Try again with different initial values.
  lambda_c0  y mu_0  x K_0  z gamma_0 alpha lambda_a0 beta d0 loglik df conv
1        NA NA   NA NA  NA NA      NA    NA        NA   NA NA     NA NA   NA
```

when called from `develop`.

Find out why that is and fix it.

**Comment by rsetienne** [comment]
This is an error in the master branch, not develop, except that the example should be changed. It should be fixed now.

**Comment by luislvalente** [comment]
The example still gives an error in the develop branch, but not in master. In master both lsodes and ode45 work. In develop, it fails with ode45 (as specified in the example). If I change to lsodes from ode45 it does work.

**Comment by rsetienne** [comment]
In master 'ode45' works because it is actually using lsodes...

Op vr 17 jul. 2020 13:52 schreef luislvalente <notifications@github.com>:
