### ISSUE TITLE
Is the cladogenesis rate correctly calculated?

### ISSUE THREAD

**Issue by Neves-P** [rsetienne/DAISIE#14]
While working on #11, I noticed the following:
The cladogenesis calculation in `get_clado_rate` is different than the one in `loglik_CS_time`.

In the `loglik_CS_time` rhs function, it is computed this way:
`lacvec <- pmax(rep(0, lnn), lac0 * (1 - nn / (area * K0)))`

while in `get_clado_rate` it is computed like this:

`clado_rate <-  max(c(
      N * lac * island_area(timeval, Apars, island_ontogeny) *
        (1 - N / (island_area(
        timeval,
        Apars,
        island_ontogeny) * K)), 0), na.rm = T)
` where island_area evaluates to area as in above.

The question is: should the `nn` vector be included in the calculation (missing in the first example)? I added this vector in 9c72df4, which makes the null-ontogeny and ontogeny likelihoods (last test of `DAISIE_test.R`) be different, implying the change is incorrect. Is the `N *` term in `get_clado_rate` incorrect, then?
Asking @rsetienne for help, please!

**Comment by rsetienne** [comment]
Hi Pedro,

I think it gets multiplied by n elsewhere. Can you check?

Cheers, Rampal

**Comment by Neves-P** [comment]
Hi @rsetienne,
Thanks for the clarification!

Indeed, I forgot about this; I believe the multiplication by n is done in the equations, example:
`dx1 =
... 
lacvec[il1] * nn[in1]...` 

This is what you mean, correct? If so, then I can't use the current rate calculation function and `sapply`. Since the clado rate there is calculated by as `N * lac * Area * (1 - N / (Area * K))` and we need to pass the correct value of N for the carrying capacity term, but not to the "island wide" rate term. I will work out a way of making this possible. I think you'd agree that it would be optimal to have the same rate functions be used for the MLE and simulation code to make sure that we don't change one of them and leave the other untouched (so the simulation and estimation rate calculation should be always equivalent).

Cheers!
Pedro

**Comment by rsetienne** [comment]
I do not follow...

**Comment by Neves-P** [comment]
Hi @rsetienne,

Sorry, I was not very clear. What I mean is that the rates, in this case cladogenesis, get multiplied by n when the equations are computed:
```R
dx1 <- 
    (laavec[il3] * xx3[ix3] + 2 * lacvec[il1] * xx3[ix1]) * (kk == 1) + 
    laavec[il1 + 1] * xx2[ix1] + lacvec[il4 + 1] * xx2[ix4] +
    muvec[il2 + 1] * xx2[ix3] + lacvec[il1] * nn[in1] * xx1[ix1] +
    muvec[il2] * nn[in2] * xx1[ix2] +
    -(muvec[il3] + lacvec[il3]) * nn[in3] * xx1[ix3] - gamvec[il3] * xx1[ix3]
```

i.e., the term `lacvec[il1] * nn[in1]` above is the multiplication of each element of the cladogenesis vector by the corresponding N, which is stored in `nn`. As this term is included in the equation, then it should not be repeated, which is what was happening as `get_clado_rate` calculates the effective rate and not the per capita rate.
To avoid this, I will modify the get_X_rate functions to return the per capita rate if so specified, while maintaining the computation general. This way we can make the rates calculation for the MLE and simulation parts of the code depend on the same modules, hopefully reducing chances of error in the future. I will make the changes and maybe we can discuss them in the next meeting 😃 

Cheers,
Pedro

**Comment by Neves-P** [comment]
This was solved ages ago and I lost the reference to where, my bad!
