### ISSUE TITLE
Less verbose Travis output

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/DAISIE#16]
I see in e.g. [Josh's Travis build](https://travis-ci.org/rsetienne/DAISIE/builds/545475504#L10000) that Travis produces 10k lines of output. Due to this, one cannot read the reason why a build fails.

I suggest to follow the UNIX Golden Rule of Silence: if everything works, no output should be produced. In our contexts: tests should not produce output (unless you test them to have output, which is very rare).

I will try to assign @Neves-P to do this, he's perfectly able to let another team member fix this, as this is a rather easy Issue :+1:

**Comment by Neves-P** [comment]
Working on it, thanks!
Must make minor changes in many examples so they don't print to the console when ran 👍

**Comment by richelbilderbeek** [comment]
Cool! Thanks a bunch :+1:

**Comment by Neves-P** [comment]
Fixed 28e6b358ebec694c9d910344a7bebe3714c928d0.

Key changes: Numerical issues encountered and incompatible K message print to console iff `verbose == TRUE`

Examples store in variables. Enough changes not to cause over > 10k lines in travis output if build fails. Can probably be trimmed down even further.

Thanks again for the tip @richelbilderbeek!
