### ISSUE TITLE
DAISIE_format_IW fails when island empty

### ISSUE THREAD

**Issue by Neves-P** [rsetienne/DAISIE#21]
If ran:
```
set.seed(1)
DAISIE::DAISIE_sim(
  time = 10,
  M = 1000,
  pars = c(1.0e+00, 4.0e-01, 1.5e+01, 1.0e-04, 2.0e-01),
  replicates = 100,
  divdepmodel = "IW"
)
```
on any branch `develop` or above format IW fails due to `btimes` being empty.

**Comment by Neves-P** [comment]
I will try to get this working in the next couple of days, @joshwlambert, @xieshu95, have you done some changes in the format IW code? If so, that's absolutely fine, it's really how it goes, don't worry! 😄 If you have, could you point me in the broad direction of what you changed?

**Comment by Neves-P** [comment]
This: https://github.com/rsetienne/DAISIE/blob/863d143d5b5a6555ee2ea5c1a9d6fb18323d57e0/R/DAISIE_format_IW.R#L31 

was the offending line. Any idea why this was added, @xieshu95, @joshwlambert, @rsetienne, @richelbilderbeek. It's totally fine, but I fear that by "fixing" it I broke something of yours!

**Comment by richelbilderbeek** [comment]
Some people have a rule: 'If it can be removed without breaking tests, it should be removed'. Or the Beyonce principle: 'If you like it, then you gotta [sic] put a test on it'.

So, well done :+1:

**Comment by joshwlambert** [comment]
I don't recognise the line, so shouldn’t affect my stuff. Thanks for fixing.

**Comment by Neves-P** [comment]
Thanks, both! 😄
