### ISSUE TITLE
Fix Pedro's build errors

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/DAISIE#6]
Pedro has some build errors in [the Travis log](https://travis-ci.org/richelbilderbeek/DAISIE/jobs/413681328#L1586). 

Who will fix this?

1) Pedro, as fixing that is part of the craft
2) Richel, as Pedro needs to focus on the presentation

Let @Neves-P choose, e.g. by assigning someone to this Issue.

**Comment by Neves-P** [comment]
I'll take care of it, @richelbilderbeek, thank you! But I can't seem to assign myself to this issue, maybe I don't have permissions to do so?

**Comment by richelbilderbeek** [comment]
Nah, you'll need to be a Collaborator to do so and only Rampal can give you this permission. As he is on holidays, I suggest we then use a social construct like posting it at an Issue :+1: :rainbow:

**Comment by Neves-P** [comment]
Sounds good! :+1:
Build errors are now fixed!

**Comment by richelbilderbeek** [comment]
Well done! Closing the Issue then :rainbow:
