### ISSUE TITLE
DAISIE_sim_with_mainland

### ISSUE THREAD

**Issue by Neves-P** [rsetienne/DAISIE#66]
- [x] Lint
- [x] Document
- [x] Coverage
- [ ] Merge

**Comment by richelbilderbeek** [comment]
I think this is mine, but maybe @joshwlambert thinks this would be a nice thing to do, as he'll know I'll fix whatever he cooks up :+1:

@joshwlambert: want this Issue? If yes, go ahead and assign yourself :rocket:

**Comment by joshwlambert** [comment]
Will do
