### ISSUE TITLE
Shu: is using both 'Tpars' and 'single_trait_state' redundant?

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/DAISIE#72]
I find these arguments:

```r
 Tpars = NULL,
  single_trait_state = TRUE,
```

I have the idea that I can safely assume:

```r
testit::assert(single_trait_state == is.null(Tpars))
```

If I am right, I suggest removing the  `single_trait_state` parameter and use `is.null(Tpars)` instead.

**Comment by xieshu95** [comment]
@richelbilderbeek  Yes Richel, you are right. I will remove the single_trait_state. Thanks a lot!

**Comment by richelbilderbeek** [comment]
I predict this has already been done by @xieshu95. Closing :+1:
