### ISSUE TITLE
Write test to crash DAISIE as discussed

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/DAISIE#81]
I just spoke with @xieshu95. She can crash DAISIE with the IW likelihood.

@xieshu95: could you write a test that reproduces this crash?

E.g., someplace in `test-[function name].R`:

```r
if (1 == 2) {
   # Issue #81
  # Test here
}
```

**Comment by xieshu95** [comment]
@richelbilderbeek ：Hi Richel, I wrote a test to check IW likelihood, and found what made R crash probably because the unsuitable initial values, if I change the initial value, it will not crash, just very slow.
I pushed it on my branch, please help me to have a look when you are free. If you find something wrong please tell me :)

**Comment by richelbilderbeek** [comment]
Will do, Tuesday between 15:00-16:00 :+1:

**Comment by richelbilderbeek** [comment]
Hi @xieshu95,

Well done!

I have two remarks

  1. Readability
  2. How to deal with the tests that crash

See below.

## 1. Readability

First, if I read this:

```r
  test_that("general DAISIE_IW", {
    pars1 <- c(0.5,0.2,20,0.002,0.1)
```

I have no idea what these parameter values are. Sure, I can look them up. Preferably write:

```r
  test_that("general DAISIE_IW", {
    extinction_rate <- ...
    anagenesis_rate <- ...
    cladogenesis_rate <- ...
   # etc.
    pars1 <- c([use those rates])
```

This will make it way easier for anyone to also see what changes between the runs.

## 2. How to deal with the tests that crash

I need your expertise here, also because I cannot read what is going wrong, due to the readability. 

My question is: do you think that the parameter settings are unrealistic/irrelevant/unbiological and the crashing is caused by this?

 * If yes: the functions should (as the mantra indicates) *fail fast* with a helpful error message. A function that assumes a certain input should check it. This may already be `DAISIE_sim`! Write tests to check that the error messages are helpful.

 * If no, let me know, after fixing point 1.

:+1:

Cheers, Richel

**Comment by richelbilderbeek** [comment]
I predict this Issue has been done :+1:
