### ISSUE TITLE
Feature request: create_daisie_pars1

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/DAISIE#82]
When calling DAISIE, we often need a `pars1`. Most of the documentation shows how to create this:

```r
pars1 <- c(1:5)
```

or

```
pars1 <- c(0.1, 0.2, Inf, 0.3, 0.4)
```

I suggest to add a function to make this more verbose:

```r
pars1 <- create_daisie_parars1(
  extinction_rate = 0.1,
  migration_rate = 0.2,
  # ... etc
)
```

I think this will make all examples more readable. Additionally, this opens up avenues to write a `check_daisie_params1`....

**Comment by richelbilderbeek** [comment]
Let's see if I can convince ~~the kids~~ my fellow PhDs to do this :+1:

**Comment by Neves-P** [comment]
Hi Richel!

We appreciate the suggest, but have decided against it for pars. We do have a similar function now called `create_default_pars()` that works in a similar way and wraps around most parameters.

Cheers! 👍
