### ISSUE TITLE
Tip: use @inheritParams

### ISSUE THREAD

**Issue by richelbilderbeek** [rsetienne/DAISIE#87]
Hi @Neves-P and other DAISIE dev,

Just a nice tip: to inherit the documentation of parameters, use `@inheritParams`, for example, from [babette](https://github.com/ropensci/babette/blob/master/R/bbt_run.R#L3):

```r
#' Do [something]
#' @inheritParams default_params_doc
# ...
```

where [default_params_doc.R](https://github.com/ropensci/babette/blob/master/R/default_params_doc.R) holds all function arguments.

This is IMHO superior to sprinkle the whole code with:

```r
#' Do [something]
#' @param a something
#' @param b something
# ...
```

Feel free to ignore, but it looks like you would enjoy this :+1:

If not, sorry for the noise :rainbow:

**Comment by Neves-P** [comment]
Hey @richelbilderbeek ! Indeed this is a great idea and something that @joshwlambert and I are planning to do very soon as part of the ongoing refactoring effort :) Thank you very much for the suggestion! 😄

**Comment by richelbilderbeek** [comment]
Happy to help :sunglasses:

**Comment by Neves-P** [comment]
In progress and wonderfully done by @joshwlambert starting here 7bbc49439819b8a0bc225016738e1589975d711b to here 8bd3c7510e8112ae35147bdfbeb17b635222bee0

**Comment by richelbilderbeek** [comment]
I feel this Issue has had its use. Closing it :+1:
